apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/pietervincken/renovate-tekton-argo-talk.git//k8s/monitoring?ref=main
  # - resources/thanos-azureidentity.yaml
  # - resources/thanos-azureidentitybinding.yaml

# thanos is currently broken.

# secretGenerator:
#   - name: thanos-objectstorage
#     files:
#       - config/thanos.yaml
#     options:
#       disableNameSuffixHash: true

# patches:
# - target:
#     kind: Prometheus
#   path: patches/thanos-config.yaml

# - target:
#     kind: StatefulSet
#     name: thanos-store
#   path: patches/thanos-store-aad.yaml

replicas:
  - name: thanos-store
    count: 0
  - name: thanos-query
    count: 0
