apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: external-dns
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: cfbb9e2b-96c1-438e-aa75-2a1722166a72
  resourceID: /subscriptions/467811c4-023c-4b77-8511-54b5b2eac549/resourceGroups/rg-renovate-talk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/external-dns-operator
  type: 0
