apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: thanos
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  clientID: 9e05210e-3471-46d2-afe8-1dd11cfee469
  resourceID: /subscriptions/467811c4-023c-4b77-8511-54b5b2eac549/resourceGroups/rg-renovate-talk/providers/Microsoft.ManagedIdentity/userAssignedIdentities/thanos
  type: 0
