- op: add
  path: /spec/target/template/data/DOCKER_RENOVATETALKACR_AZURECR_IO_USERNAME
  value: "{{ .ACR_USERNAME }}"
- op: add
  path: /spec/target/template/data/DOCKER_RENOVATETALKACR_AZURECR_IO_PASSWORD
  value: "{{ .ACR_PASSWORD }}"
- op: add
  path: /spec/data/-
  value:
    secretKey: ACR_USERNAME
    remoteRef:
      key: acr-username
- op: add
  path: /spec/data/-
  value:
    secretKey: ACR_PASSWORD
    remoteRef:
      key: acr-password
