apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/pietervincken/renovate-tekton-argo-talk.git//k8s/renovate?ref=main

patches:
  - target:
      name: renovate-env
      kind: ExternalSecret
      group: external-secrets.io
    path: patches/renovate-secret.yaml
