apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aad-pod-identity
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: git@github.com:pietervincken/k8s-on-azure.git
    targetRevision: main
    path: k8s/aad-pod-identity
  destination:
    server: https://kubernetes.default.svc
    namespace: aad-pod-identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
